GLOBAL:
  log_file: # delete this to output log to stderr
  history:
    max_num: 300 # max history record nums
    save_to: # default: ./.t-rss_History
  timeout: 1m # {int}s/m/h/d

TASKS:
  Name_of_task0:
    rss:
      url: https://example.com
      method: GET #*delete this except you know what this means
      headers:    #*if needed
        Cookie: something
        Key: Value
      interval: 10s # {int}s/m/h/d
    filter:
      content_size:
        min: 10MB340KB
        max: 120G10MB
      regexp:
        accept:
          - A
        reject:
          - B
    quota:
      num: 65535
      size: 100G
    edit:
      tracker:
        delete:
          - share
        add:
          - http(s)://example.com/
    receiver:
      delay: 12s
      save_path: /home/WatchDir/
      client:
        Name_of_client0:
          type: qBittorrent
          url: http://127.0.0.1
          username: admin
          password: adminadmin
          dlLimit:
          upLimit:
          paused: true
          savepath: /home/Downloads
        Name_of_client1:
          type: Deluge
          host: 127.0.0.1:1234
          username:
          password:

  Name_of_task1:
    rss:
      url: https://example.com
    receiver:
      save_path: /home/WatchDir/
  Name_of_task2:
    rss:
      url: https://example.com
    receiver:
      save_path: /home/WatchDir/
    